# Generated by Django 6.0.5 on 2026-06-05 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_name',
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='Untitled Project', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='assigned_tl',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'tl'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
