# Generated by Codex on 2026-06-09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_address_user_age_user_dob_user_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamGroup',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'manager',
                    models.ForeignKey(
                        limit_choices_to={'role': 'manager'},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='managed_groups',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='TeamGroupLeader',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'group',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='leader_assignments',
                        to='accounts.teamgroup',
                    ),
                ),
                (
                    'team_leader',
                    models.ForeignKey(
                        limit_choices_to={'role': 'tl'},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='group_leader_assignments',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'unique_together': {('group', 'team_leader')},
            },
        ),
        migrations.CreateModel(
            name='TeamGroupMember',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'group',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='member_assignments',
                        to='accounts.teamgroup',
                    ),
                ),
                (
                    'member',
                    models.ForeignKey(
                        limit_choices_to={'role': 'member'},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='group_member_assignments',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'team_leader',
                    models.ForeignKey(
                        limit_choices_to={'role': 'tl'},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='assigned_group_members',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'unique_together': {('group', 'member')},
            },
        ),
        migrations.AddField(
            model_name='teamgroup',
            name='team_leaders',
            field=models.ManyToManyField(
                limit_choices_to={'role': 'tl'},
                related_name='team_groups',
                through='accounts.TeamGroupLeader',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
