# Generated by Django 6.0.2 on 2026-06-04 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="progressupdate",
            old_name="progress_percentage",
            new_name="progress",
        ),
    ]
